server:
  port: 9001
  # 启用HTTP/2
  http2:
    enabled: true
  undertow:
    io-threads: 16
    worker-threads: 128
    buffer-size: 512
  # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true

spring:

  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/stu_vite?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  application:
    name: users-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
#  config:
#    import:
#      - nacos:nacos-config-example.properties?refreshEnabled=true
management:
  endpoints:
    web:
      exposure:
        include*=:
